version: '3.8'

services:
  db:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_USER: menocal
      POSTGRES_PASSWORD: PwdPostgresRJMC17
      POSTGRES_DB: learning-sytem
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
